### ISSUE TITLE
Empty files in dataset: HP-NEURO

### ISSUE THREAD

**Issue by dongkwan-kim** [mims-harvard/SubGNN#8]
Hi, I really appreciate the detailed description and instruction in running codes and datasets.

I found that there are multiple empty files in the HP-NEURO folder you provided.

https://www.dropbox.com/sh/zv7gw2bqzqev9yn/AABa4J3UlMDkbbcksYKKHrgKa/hpo_neuro?dl=0&subfolder_nav_tracking=1

Would you please check this?

Thanks in advance.

**Comment by EmilyAlsentzer** [comment]
Hi @dongkwan-kim, Are you referring to the `similarities` folder? All of the files in that folder are generated by running the code if they do not already exist. You should still be able to run everything without the files there, but I just added the similarity pre-computations for `HPO-NEURO` so that you don't need to recalculate them. If there's something else missing from the folder, please let me know.

**Comment by dongkwan-kim** [comment]
Thank you for adding `similarities` files.

But empty files I am saying are `degree_sequence.txt`, `edge_list.txt`. `ego_graphs.txt`, `gin_embeddings.pth`, `graphsaint_gcn_embedddings.pth`, and `shortest_path_matrix.npy` in `hpo_neuro/`.

These files are 0-bytes files to me on the dropbox preview and my filesystem after download.

I think there seems to be an error when uploading `hpo_neuro/` to the dropbox. (There is no error for other datasets as far as I can see..)

Here is a screenshot for 0-bytes `ego_graphs.txt` as an example.

![image](https://user-images.githubusercontent.com/14350049/100245186-1c775e80-2f7b-11eb-8d4e-433b87f41c7d.png)


Or..., am I missing something?

**Comment by EmilyAlsentzer** [comment]
I see, I think this occurred because the `HPO-NEURO` files were symbolic links to `HPO-METAB` (the datasets share the same base underlying graph). I have updated the dropbox so that these files are no longer empty. Let me know if you have any more trouble.

**Comment by dongkwan-kim** [comment]
Oh, I see. Thank you for your effort. I will close this issue.
